"""
SQLAlchemy ORM Models for Phase 8: Smart Irrigation and Crop Recommendation
"""
from datetime import datetime
from sqlalchemy import Column, Integer, String, Float, Text, DateTime, Boolean, ForeignKey, UniqueConstraint
from sqlalchemy.orm import relationship
from backend.app.db.database import Base


class IrrigationLog(Base):
    __tablename__ = "irrigation_logs"

    id = Column(Integer, primary_key=True, index=True)
    farmer_id = Column(Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True, index=True)
    crop_name = Column(String(100), nullable=False)
    soil_type = Column(String(100), nullable=False)
    field_size_hectares = Column(Float, default=1.0)
    moisture_15cm = Column(Float, nullable=False)
    moisture_30cm = Column(Float, nullable=False)
    ambient_temp = Column(Float, nullable=False)
    relative_humidity = Column(Float, nullable=False)
    rain_forecast_mm = Column(Float, default=0.0)
    status = Column(String(50), nullable=False)  # 'Immediate', 'Scheduled', 'Adequate', 'Waterlogged'
    water_amount_litres_per_ha = Column(Float, default=0.0)
    drip_duration_mins = Column(Integer, default=0)
    explanation = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    farmer = relationship("User", backref="irrigation_logs", foreign_keys=[farmer_id])


class CropRecommendationRecord(Base):
    __tablename__ = "crop_recommendations"

    id = Column(Integer, primary_key=True, index=True)
    farmer_id = Column(Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True, index=True)
    nitrogen = Column(Float, nullable=False)
    phosphorus = Column(Float, nullable=False)
    potassium = Column(Float, nullable=False)
    ph = Column(Float, nullable=False)
    temperature = Column(Float, nullable=False)
    humidity = Column(Float, nullable=False)
    rainfall = Column(Float, nullable=False)
    top_crop_1 = Column(String(100), nullable=False)
    confidence_1 = Column(Float, nullable=False)
    top_crop_2 = Column(String(100), nullable=True)
    confidence_2 = Column(Float, nullable=True)
    top_crop_3 = Column(String(100), nullable=True)
    confidence_3 = Column(Float, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    farmer = relationship("User", backref="crop_recommendations", foreign_keys=[farmer_id])


class DiseaseDiagnosisRecord(Base):
    """
    Persisted crop disease observation record generated by AI model or field scouting.
    Links directly to the Farmer who ran the diagnostic.
    """
    __tablename__ = "disease_diagnoses"

    id = Column(Integer, primary_key=True, index=True)
    farmer_id = Column(Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True, index=True)
    crop = Column(String(80), nullable=False)
    disease = Column(String(150), nullable=False)
    confidence = Column(Float, nullable=False)
    confidence_str = Column(String(20), nullable=True)
    status = Column(String(50), nullable=False)  # 'Healthy', 'Diseased', 'Low Confidence'
    pathogen = Column(String(150), nullable=True)
    symptoms = Column(Text, nullable=True)
    treatment = Column(Text, nullable=True)
    image_filename = Column(String(255), nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    farmer = relationship("User", backref="disease_diagnoses", foreign_keys=[farmer_id])


class IoTSensorReading(Base):
    __tablename__ = "iot_sensor_readings"

    id = Column(Integer, primary_key=True, index=True)
    device_id = Column(String(50), default="AGRI-NODE-01")
    soil_moisture_15cm = Column(Float, nullable=False)
    soil_moisture_30cm = Column(Float, nullable=False)
    soil_temp = Column(Float, nullable=False)
    electrical_conductivity = Column(Float, nullable=False)
    battery_level = Column(Float, default=98.0)
    timestamp = Column(DateTime, default=datetime.utcnow)


class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    full_name = Column(String(120), nullable=False)
    email = Column(String(150), unique=True, index=True, nullable=False)
    password_hash = Column(String(255), nullable=False)
    salt = Column(String(64), nullable=False)
    farm_name = Column(String(150), nullable=True)
    farm_location = Column(String(150), nullable=True)
    preferred_crop = Column(String(80), nullable=True)
    role = Column(String(50), default="FARMER", nullable=False)  # 'FARMER', 'AGRICULTURAL_STAKEHOLDER', 'AGRICULTURAL_EXPERT', 'ADMIN'
    is_active = Column(Boolean, default=True, nullable=False)
    organization_name = Column(String(150), nullable=True)
    organization_type = Column(String(100), nullable=True)
    operating_regions = Column(String(255), nullable=True)
    primary_crops = Column(String(255), nullable=True)
    stakeholder_type = Column(String(100), nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)


class StakeholderFarmerRelationship(Base):
    """
    Explicit relationship connecting an Agricultural Stakeholder to a Farmer.
    Controls mutual visibility and agricultural data sharing.
    Supported statuses: 'PENDING', 'ACTIVE', 'REJECTED', 'REMOVED'
    """
    __tablename__ = "stakeholder_farmer_relationships"
    __table_args__ = (
        UniqueConstraint("stakeholder_id", "farmer_id", name="uq_stakeholder_farmer"),
    )

    id = Column(Integer, primary_key=True, index=True)
    stakeholder_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    farmer_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    status = Column(String(20), default="PENDING", nullable=False, index=True)  # PENDING, ACTIVE, REJECTED, REMOVED
    notes = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    stakeholder = relationship("User", foreign_keys=[stakeholder_id], backref="connected_farmer_relations")
    farmer = relationship("User", foreign_keys=[farmer_id], backref="stakeholder_connections")



